version: '3'

services:
  web:
    build: .
    image: joxmar/docker-react
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    stdin_open: true

  tests:
    build: .
    volumes:
      - .:/app
    command: ['yarn', 'test']
    stdin_open: true
